import crypto from 'node:crypto';
import { readDatabase, writeDatabase } from '../_github.js';
import { verifyOTPToken, createUserToken } from '../_auth.js';
import { safeUser } from '../_store.js';
import { createRegistrationTicket, verifySignedRegistrationTicket } from '../_registration.js';
import { getMainGateway, gatewayFetch } from '../_whatsapp.js';
import { env } from '../_env.js';
import { randomSn } from '../_finance.js';

function finish(user, database, sha, req){
  user.googlePendingVerification=false; user.failedLoginAttempts=0; user.lastLoginAt=new Date().toISOString(); const ua=String(req.headers?.['user-agent']||''); user.lastLoginIp=String(req.headers?.['cf-connecting-ip']||req.headers?.['x-forwarded-for']||'').split(',')[0].trim(); user.lastLoginDevice=/Mobile|Android|iPhone|iPad/i.test(ua)?'Mobile':'Desktop';user.lastLoginBrowser=/Chrome/i.test(ua)?'Chrome':/Firefox/i.test(ua)?'Firefox':/Safari/i.test(ua)?'Safari':/Edge/i.test(ua)?'Edge':'Browser'; return writeDatabase(database,sha,`Google verification ${user.username}`).then(()=>({success:true,user:safeUser(user),token:createUserToken(user.id),next:'#store'}));
}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({success:false,message:'Method tidak diizinkan.'});try{const action=String(req.body?.action||'');const ticket=verifySignedRegistrationTicket(req.body?.verificationToken);if(!ticket||ticket.type!=='google_verify'||!ticket.userId||!ticket.email)return res.status(401).json({success:false,message:'Sesi verifikasi Google tidak valid atau sudah kedaluwarsa.'});const {database,sha}=await readDatabase();const user=(database.users||[]).find(u=>u.id===ticket.userId&&String(u.email||'').toLowerCase()===String(ticket.email).toLowerCase());if(!user)return res.status(404).json({success:false,message:'User Google tidak ditemukan.'});if(action==='otp'){const otp=String(req.body?.otp||'').trim(),otpToken=String(req.body?.otpToken||'');if(!verifyOTPToken(otpToken,ticket.email,otp))return res.status(400).json({success:false,message:'OTP salah atau kedaluwarsa.'});return res.status(200).json(await finish(user,database,sha,req));}if(action==='whatsappStart'){const sn=randomSn('GOOGLE');const g=await getMainGateway();const phone=String(g?.ownerPhone||env('BOT_OWNER_PHONE','')).replace(/\D/g,'');if(!phone)return res.status(503).json({success:false,message:'Nomor bot admin_utama belum dikonfigurasi.'});user.googleWhatsappVerification={sn,expiresAt:new Date(Date.now()+15*60*1000).toISOString(),createdAt:new Date().toISOString()}; user.lastVerificationSN=sn;await writeDatabase(database,sha,`Google WhatsApp verification ${user.username}`);const text=`${sn}\n\nSaya ingin memverifikasi login Google ke RYY-STORE dengan Email: ${ticket.email}\n\n_*Jangan ubah pesan ini!*_`;return res.status(200).json({success:true,sn,waUrl:`https://wa.me/${phone}?text=${encodeURIComponent(text)}`,expiresAt:user.googleWhatsappVerification.expiresAt});}if(action==='whatsappCheck'){const pending=user.googleWhatsappVerification;if(!pending||new Date(pending.expiresAt)<new Date())return res.status(410).json({success:false,message:'Sesi WhatsApp sudah kedaluwarsa.'});const g=await getMainGateway();if(!g)return res.status(503).json({success:false,message:'Gateway admin_utama belum siap.'});let st;try{st=await gatewayFetch(g,'/status',{method:'GET'});}catch{return res.status(502).json({success:false,message:'Bot admin_utama belum dapat dihubungi.'});}const hit=(st.messages||[]).find(m=>!String(m.sender||m.chat||m.from||'').toLowerCase().includes('@newsletter')&&String(m.text||m.message||'').includes(pending.sn));if(!hit)return res.status(200).json({success:true,verified:false,message:'Pesan WhatsApp belum terdeteksi.'});delete user.googleWhatsappVerification;return res.status(200).json(await finish(user,database,sha,req));}return res.status(400).json({success:false,message:'Action verifikasi Google tidak dikenal.'});}catch(e){console.error(e);return res.status(500).json({success:false,message:e?.message||'Verifikasi Google gagal.'});}}
